modLoader = "javafml"
loaderVersion = "[47,)"
license = "AGPL-3.0"
issueTrackerURL = "https://github.com/infernalstudios/Infernal-Expansion-Redux/issues"

[[mods]]
modId = "infernalexp"
version = "${version}"
displayName = "Infernal Expansion"
authors = "evanbones, Lyof, Nekomaster"
description = "Expanding the Nether beyond its official update with tons of new mobs & blocks, all while staying true to the Vanilla feel!"
logoFile = "icon.png"

[[dependencies.infernalexp]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.infernalexp]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.infernalexp]]
modId = "geckolib"
mandatory = true
versionRange = "[4.4.7,5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.infernalexp]]
modId="cloth_config"
mandatory=false
versionRange="[11.1.136,)"
ordering="NONE"
side="BOTH"